### ISSUE TITLE
[Request] Add 32x32 or something if thats possible xd

### ISSUE THREAD

**Issue by xhendrikg** [KevinWh0/BundleArtGenerator#12]

**Comment by ChaoticLeah** [comment]
Sorry, but I have already tried this and it creates too long of a command for command blocks....

**Comment by xhendrikg** [comment]
> Sorry, but I have already tried this and it creates too long of a command for command blocks....

https://youtu.be/5m1LAXj5oRo *explain meme* haha

**Comment by ChaoticLeah** [comment]
Hmm, thats because they are using functions, they might have a larger limit.

**Comment by ChaoticLeah** [comment]
I don't think I will be adding support for this any time soon since that is a completely different thing and its way more complicated to use.
