### ISSUE TITLE
Not working right?

### ISSUE THREAD

**Issue by xhendrikg** [KevinWh0/BundleArtGenerator#5]
![grafik](https://user-images.githubusercontent.com/69456711/113202837-90987a80-926b-11eb-982d-f25b921e2e7b.png)
There are the X'es and a white pane (looks like it) but when u "unpack" the bundle it doesnt drop one white. Version: 21w13a Command: `give @p bundle{Items:[{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b},{id:"minecraft:black_stained_glass_pane",Count:1b}]}`

**Comment by ChaoticLeah** [comment]
I have looked over the command, and there is nothing about white stained glass, so my guess is its some sort of Minecraft bug. The fact that it does not drop the white one further suggests its a Minecraft bug. As for the X's, I don't know what that is, but what I do know is that this bundle art program does not work every single time, and I believe this is just due to Minecraft and how it displays it. Bundles were never made for bundle art so that might be why.

**Comment by ChaoticLeah** [comment]
Cant fix this, this is Minecrafts doing and I cant change their code. Sorry.

**Comment by ChaoticLeah** [comment]
It seems minecraft has updated in the snapshots and therefor it needs a bit of a rework. Currently I dont know the solution so it may take a little.

**Comment by ChaoticLeah** [comment]
After doing some tests it seems that this is minecraft acting weird, but the best fix I have for now is to remove the bottom right pixel. Perhaps in the UI revamp I will make it so you can select what version you want to use since it seems to be changing all the time. For now I will add a quickfix that just removes the bottom right pixel and you can see if that fixes it for you
![image](https://user-images.githubusercontent.com/45321184/113379190-abcbbe80-932d-11eb-8b7b-8b7e742d3a45.png)

**Comment by ChaoticLeah** [comment]
This fix seems to have fixed this problem for the most part. I don't think I can fix the other problems. This is the how the bundle art looks now:

![image](https://user-images.githubusercontent.com/45321184/113380760-eafc0e80-9331-11eb-9ed2-458db2a1bfcc.png)

Also thanks for the feedback!

**Comment by xhendrikg** [comment]
![grafik](https://user-images.githubusercontent.com/69456711/113405195-b6c43480-93a9-11eb-9235-797321f5ce65.png)
(The white at the left corner is every time)

**Comment by ChaoticLeah** [comment]
yea, that is something that minecraft does and therefor I cant provide a fix for it.
